# The ids, published where the code can find them.
#
# The knowledge_base and data_source ids are generated by AWS, so they cannot be
# committed defaults the way DEFAULT_TOP_K and DEFAULT_QDRANT_URL are. Terraform
# writes them to these paths and the *path* becomes the committed constant, with
# whatever the current stack produced behind it. A fresh clone with AWS
# credentials works with no manual step.
#
# This also closes, for project 02, the loose end project 01 still carries: its
# SSM parameters were made by hand and are not in infra/, so a rebuild from
# Terraform would not recreate them.

resource "aws_ssm_parameter" "knowledge_base_id" {
  name  = "/${var.name_prefix}/knowledge-base-id"
  type  = "String"
  value = aws_bedrockagent_knowledge_base.main.id
}

resource "aws_ssm_parameter" "data_source_id" {
  name  = "/${var.name_prefix}/data-source-id"
  type  = "String"
  value = aws_bedrockagent_data_source.main.data_source_id
}
