"""Builds the settings the rest of the app runs on, and checks them first.

Pure by construction: every value arrives as an argument, so this module never
reaches the network and its tests never need AWS. The ids come from
parameters.py, the only module that talks to SSM; main.py composes the two.

Project 01's config carries chunk_size and chunk_overlap because its own code
does the splitting. Project 02's does not: the knowledge_base chunks, so those
settings live in infra/core as Terraform variables. The absence is the managed
pipeline showing up in the shape of the code.
"""

from collections.abc import Mapping
from dataclasses import dataclass

DEFAULT_REGION = "us-east-1"
# 8 to match project 01's shipped TOP_K, which slice 3 has to hold fixed for the
# benchmark to compare anything. See designs/skeleton.md.
DEFAULT_TOP_K = 8


@dataclass(frozen=True)
class Config:
    # Generated by AWS, published to SSM by Terraform. No committed default is
    # possible, which is why parameters.py exists at all.
    knowledge_base_id: str
    data_source_id: str
    region: str
    # Bedrock calls this numberOfResults. Named for project 01's word here so
    # the two pipelines read alike; kb_client translates at the AWS boundary.
    top_k: int


def _whole_number(env: Mapping[str, str], name: str, default: int) -> int:
    # `or default` rather than a two-argument get: an exported-but-empty
    # variable means unset, not zero.
    raw = env.get(name) or default
    try:
        return int(raw)
    except ValueError:
        raise ValueError(f"{name} must be a whole number, got {raw!r}") from None


def load_config(env: Mapping[str, str], parameters: Mapping[str, str]) -> Config:
    return Config(
        knowledge_base_id=parameters["knowledge_base_id"],
        data_source_id=parameters["data_source_id"],
        region=env.get("AWS_REGION") or DEFAULT_REGION,
        top_k=_whole_number(env, "TOP_K", DEFAULT_TOP_K),
    )
